# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Infusing Computing Webseries
email: wiobyrne@gmail.com
description: "The Infusing Computing Webseries explores the opportunities to embed computational thinking (CT) into middle school and high school classrooms."
subtitle: "A discussion from the intersection of computational thinking & the content areas."
lang: en-us
author: Ian O'Byrne
copyright: "CC-BY 4.0"
baseurl: "/infusing-computing-pod" # the subpath of your site, e.g. /blog
url: "https://wiobyrne.github.io" # the base hostname & protocol for your site
twitter_username: wiobyrne
github_username:  wiobyrne

permalink: /:year/:title.html

#Timezone
timezone: United States/New York

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-minimal
